name: XAUUSD Signal Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test workflow
        run: |
          echo "XAUUSD Signal Bot is running"
          date
