name: XAUUSD Signal Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Send test notification
        env:
          ONESIGNAL_REST_API_KEY: ${{ secrets.ONESIGNAL_REST_API_KEY }}

        run: |
          curl --fail-with-body --request POST \
            --url https://api.onesignal.com/notifications \
            --header "Authorization: Key $ONESIGNAL_REST_API_KEY" \
            --header "Content-Type: application/json" \
            --data '{
              "app_id": "092fc306-c2ab-4a85-a3f9-ff8b50dd8833",
              "include_subscription_ids": [
                "cdcd03a6-7830-4621-9178-8fb9cc306b8e"
              ],
              "headings": {
                "en": "🟢 XAUUSD Signal Bot"
              },
              "contents": {
                "en": "🔔 إشعار تجريبي مباشر إلى جهازك. البوت متصل بـ OneSignal."
              }
            }'